# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_table',
            name='admin',
        ),
        migrations.AddField(
            model_name='task_table',
            name='admin',
            field=models.ManyToManyField(to='quickstart.user_db'),
        ),
    ]
