# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-03 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20170403_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_table',
            name='admin',
        ),
        migrations.AddField(
            model_name='task_table',
            name='admin',
            field=models.ForeignKey(default=datetime.datetime(2017, 4, 3, 1, 16, 31, 643598, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='quickstart.user_db'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task_table',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task_table',
            name='assignee',
            field=models.ManyToManyField(related_name='student', to='quickstart.user_db'),
        ),
    ]
